services:
  - type: web
    name: music-locker-v1
    runtime: docker
    repo: https://github.com/your-username/MusicLocker-PHP
    region: singapore
    plan: starter

    dockerfilePath: Dockerfile
    dockerContext: .

    autoDeploy: true
    maxInstances: 2
    minInstances: 1

    healthCheckPath: /

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Manila
      - key: LOG_LEVEL
        value: error
